### ISSUE TITLE
Pipeline of commands.

### ISSUE THREAD

**Issue by AntonXue** [BillHallahan/G2#12]
Enable end user of G2 to quickly perform symbolic execution by supplying an easy pipeline of something like `Interface.go` functions.

e.g.:
```Haskell
main = do
    ...
    g2_core    <- Translator.Interface.go        filename
    prep_core  <- Preprocessing.Interface.go     g2_core
    sym_states <- SymbolicExecution.Interface.go pp_core
    solved     <- SMT.Interface.go               sym_states
    ....
```

Exact feeding of these `Interface.go` functions is to be determined, but this will dramatically lower the level of understanding that end users will actually have to understand about G2 internals in order to use it effectively.

**Comment by BillHallahan** [comment]
We have something close to this with the interface files.

**Comment by BillHallahan** [comment]
We have something close to this with the interface files.

**Comment by AntonXue** [comment]
G2 has an issue tracker?!
