### ISSUE TITLE
Liquid flag (--liquid & --liquid-func)

### ISSUE THREAD

**Issue by Alf0nso** [BillHallahan/G2#160]
Hey hey,

I had some problems running the tool with cabal.. When running with stack it works if the following extra dependency is added:
- optparse-applicative-0.17.0.0@sha256:0713e54cbb341e5cae979e2ac441eb3a5ff42e303001f432bd58c19e5638bdda,4967

While following the instructions from the readme file, the "Reachability" example works. But the LiquidHaskell example fails by saying that "--liquid" is not a valid flag.
I would like to ask if this is a functionality that was removed or if I am doing something wrong

**Comment by BillHallahan** [comment]
The LiquidHaskell debugging is still supported, but the input interface was changed and the README was never updated.  Thanks for the report- I've fixed the README.  The new input uses a separate exe:
`cabal run G2LH ./tests/Liquid/Peano.hs add`
