### ISSUE TITLE
G2: WalkerFunc bad argument passed

### ISSUE THREAD

**Issue by QHWU1228** [BillHallahan/G2#237]
Now discovered that G2: WalkerFun is having an issue with GADT syntax specifically if we have 
data MyList a where
  Ni :: MyList a
  Cons :: a -> MyList a -> MyList a
But if we have data MyList a = Ni | Cons a (MyList a) which is the same thing as above, G2 will work. Now we should consider how to make G2 understand and successfully process the GADT syntax

**Comment by BillHallahan** [comment]
Addressed by #239
