### ISSUE TITLE
Unexpected results with integer division 

### ISSUE THREAD

**Issue by florentc** [BillHallahan/G2#77]
Take the following function and symbolically evaluates in G2 with `--n 1200` reduction steps.

```haskell
foo :: Integer -> Bool
foo x = (div x 2) > 1
```

G2 generates a few concrete values for branches leading to `True` including `2` or `3` which do not check the predicate `foo`.

**Comment by BillHallahan** [comment]
Thanks for the report @florentc! This has now been fixed on the master branch.  The fix required changes both to G2 and the base library, so please:
* repull G2
* then either repull the base library manually, or rerun `bash base_setup.sh`
